language: node_js
node_js:
  - 10
os:
  - linux
  - osx
  - windows
# This (filter_secrets) is generally unsafe, but we only run builds for master,
# so it is acceptable. If we remove the branch restriction, remove this too.
# If Windows builds on Travis are fixed, and work when secrets are in use,
# remove this too.
filter_secrets: false
matrix:
  allow_failures:
    - os: windows
env:
  - YARN_GPG=no
if: branch = master OR tag IS present
dist: xenial
addons:
  apt:
    packages:
      - libudev-dev
cache: yarn
install:
  - cd $HOME
  - pwd
#  - git clone git@github.com:dygmalab/chrysalis-api
  - git clone https://github.com/0957758592/chrysalis-api.git
  - cd chrysalis-api
  - git checkout i380_flasher
  - yarn 
  - ./node_modules/.bin/lerna run build
  - cd packages/chrysalis-hardware-dygma-raise-ansi/
  - yarn link
  - cd -
  - cd packages/chrysalis-hardware-dygma-raise-iso/
  - yarn link
  - cd -
  - cd packages/chrysalis-flash/
  - yarn link
  - cd -
  - cd $TRAVIS_BUILD_DIR
  - yarn install --network-timeout 1000000
script:
  - yarn link '@chrysalis-api/hardware-dygma-raise-ansi'
  - yarn link '@chrysalis-api/hardware-dygma-raise-iso'
  - yarn link '@chrysalis-api/flash'
  - yarn run build:$TRAVIS_OS_NAME
after_script:
  - yarn add --dev aws-sdk
  - tools/s3-upload.js
